const kJWTTokenSecureStorageKey = "_delivery_hexa_jwt_token";
const kUIDSecureStorageKey = "_delivery_hexa_uid";
const double kScrollThreshold = 200.0;
const Duration kFetchThreshold = Duration(milliseconds: 1000);
const String kDeliveryDeployURI = "delivery.hexa.pro/";
const String kDeliveryTestURI = "delivery.hexa.pro/test";
const String kDeliveryTestServerActivator = "delivery@test";
bool kDeliveryTestModeOn = false;
String get kDeliveryURI => kDeliveryTestModeOn ? kDeliveryTestURI : kDeliveryDeployURI;