// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmBC5IV5oW4ROD4Dt12cg6L00qqPtn0fo',
    appId: '1:252197217731:web:51f353a041a6541ebd8976',
    messagingSenderId: '252197217731',
    projectId: 'hexa-delivery',
    authDomain: 'hexa-delivery.firebaseapp.com',
    databaseURL: 'https://hexa-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'hexa-delivery.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywuerM00rRH2zvMa4vmpjvQVzQGh8ffI',
    appId: '1:252197217731:android:b1505a01ad7e5c15bd8976',
    messagingSenderId: '252197217731',
    projectId: 'hexa-delivery',
    databaseURL: 'https://hexa-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'hexa-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcpMPaIGayhXd__yCYUiHBwbQB6YQKbk',
    appId: '1:252197217731:ios:cb25f3072956148fbd8976',
    messagingSenderId: '252197217731',
    projectId: 'hexa-delivery',
    databaseURL: 'https://hexa-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'hexa-delivery.appspot.com',
    iosClientId:
        '252197217731-mg3uam4ggddnulmu528p9ht97b12oqid.apps.googleusercontent.com',
    iosBundleId: 'com.example.hexaDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjcpMPaIGayhXd__yCYUiHBwbQB6YQKbk',
    appId: '1:252197217731:ios:cb25f3072956148fbd8976',
    messagingSenderId: '252197217731',
    projectId: 'hexa-delivery',
    databaseURL: 'https://hexa-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'hexa-delivery.appspot.com',
    iosClientId:
        '252197217731-mg3uam4ggddnulmu528p9ht97b12oqid.apps.googleusercontent.com',
    iosBundleId: 'com.example.hexaDelivery',
  );
}
