# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end

before_all do
  app_store_connect_api_key(
    key_id: "995Z5S52DH",
    issuer_id: "758f271c-fb0d-4dca-8162-38f2dee52d27",
    key_filepath: "#{ENV["FASTLANE_KEY_FILEPATH"]}", # "/Users/hexa/Documents/hexa_delivery.p8"
  )
end